[package]
name = "lol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
riven = "2.13.0"
tokio = { version = "1.26", features = ["rt-multi-thread"] }
